// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjNM11aRUOgepNjLO_vBQ9qGbT9y8OfhM',
    appId: '1:506945347137:web:f08747d588005b8cc2f0c0',
    messagingSenderId: '506945347137',
    projectId: 'soka-1a9f3',
    authDomain: 'soka-1a9f3.firebaseapp.com',
    databaseURL: 'https://soka-1a9f3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soka-1a9f3.firebasestorage.app',
    measurementId: 'G-3LVHKKXP9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmRvL3iF2-GGvodPyRVElx53osMGA8_hQ',
    appId: '1:506945347137:android:5d6d3a4bea193b4cc2f0c0',
    messagingSenderId: '506945347137',
    projectId: 'soka-1a9f3',
    databaseURL: 'https://soka-1a9f3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soka-1a9f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRAodejNFaybcXyxfqoJpt8wY-HAsyB9w',
    appId: '1:506945347137:ios:3b4c6eea54fbc78cc2f0c0',
    messagingSenderId: '506945347137',
    projectId: 'soka-1a9f3',
    databaseURL: 'https://soka-1a9f3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soka-1a9f3.firebasestorage.app',
    androidClientId: '506945347137-ps39oltjo45of0pafkjr05ao0kucgjm4.apps.googleusercontent.com',
    iosClientId: '506945347137-pfta1ugsaur5onv4c58vilt30tbm13pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.soka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRAodejNFaybcXyxfqoJpt8wY-HAsyB9w',
    appId: '1:506945347137:ios:3b4c6eea54fbc78cc2f0c0',
    messagingSenderId: '506945347137',
    projectId: 'soka-1a9f3',
    databaseURL: 'https://soka-1a9f3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soka-1a9f3.firebasestorage.app',
    androidClientId: '506945347137-ps39oltjo45of0pafkjr05ao0kucgjm4.apps.googleusercontent.com',
    iosClientId: '506945347137-pfta1ugsaur5onv4c58vilt30tbm13pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.soka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjNM11aRUOgepNjLO_vBQ9qGbT9y8OfhM',
    appId: '1:506945347137:web:30d309c5af21ba57c2f0c0',
    messagingSenderId: '506945347137',
    projectId: 'soka-1a9f3',
    authDomain: 'soka-1a9f3.firebaseapp.com',
    databaseURL: 'https://soka-1a9f3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soka-1a9f3.firebasestorage.app',
    measurementId: 'G-2MEFPKTE2Q',
  );

}